name: "test itself"
on:
  pull_request:
    types: [closed]
jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-16.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: infra/actions/test
